FROM ubuntu:bionic
RUN apt-get update
RUN yes | apt-get install wget sudo
RUN wget flopoco.gforge.inria.fr/install_scripts/install-full-gitmaster-on-bionic64.sh
RUN yes | sh install-full-gitmaster-on-bionic64.sh

VOLUME ["/flopoco_workspace"]

ENTRYPOINT ["/flopoco/build/flopoco"]

WORKDIR /flopoco_workspace
