# PyTorch build steps template with Windows images Azure DevOps Instances
#
# This build depends on 3 parameters set as environment variables in the pipeline:
#   - AZURE_DEVOPS_CLI_PAT: Secret var for authenticating to Azure DevOps
#   - AZURE_DEVOPS_ARTIFACTS_ORGANIZATION: Azure Artifacts Organization name to publish artifacts
#   - AZURE_DEVOPS_ARTIFACTS_PROJECT: Azure Artifacts Project name to publish artifacts

parameters:
  name: ''
  pool: ''
  os: ''
  cuda: ''
  is_ci_build: False
  is_official_build: False
  is_daily_build: False
  build_stage: False
  verify_stage: False
  publish_stage: False
  customMatrixes: ''

jobs:
- job: ${{parameters.name}}
  timeoutInMinutes: 300
  strategy:
    matrix:
      ${{ insert }}: ${{parameters.customMatrixes}}
  pool:
    name: ${{ parameters.pool}}
  variables:
    CMAKE_GENERATOR: Ninja
    PACKAGE_PDBS: 0

  steps:
  # Prepare for PyTorch build on Windows
  - template: prepare-build-template.yml
    parameters:
      configuration: $(configuration)
      build_stage: ${{ parameters.build_stage}}

  # Build Stage
  - ${{ if eq(parameters.build_stage, 'True') }}:
    # Set up environment variables for specific pipeline build
    - template: set-environment-variables.yml
      parameters:
        os: ${{ parameters.os}}
        cuda: ${{ parameters.cuda}}
        is_official_build: ${{ parameters.is_official_build}}

    # Sync and update PyTorch submodules
    - script: git submodule update --init --recursive --jobs 0
      displayName: Update PyTorch submodules

    # Build PyTorch and run unit tests - no packaging
    - ${{ if or(eq(parameters.is_ci_build, 'True'), eq(parameters.is_daily_build, 'True')) }}:
      # Build PyTorch from source in develop mode with Ninja
      - script: call activate $(configuration) && python setup.py develop
        displayName: Build PyTorch from source

      - ${{ if eq(parameters.is_ci_build, 'True') }}:
        # Run TestTorch unit tests to demonstrate successful PyTorch build
        - script: call activate $(configuration) && python test\test_torch.py TestTorch
          displayName: Run TestTorch unit tests

      - ${{ if eq(parameters.is_daily_build, 'True') }}:
        # Run all unit tests to demonstrate successful PyTorch build
        - script: call activate $(configuration) && python test/run_test.py --continue-through-error --exclude-jit-executor --verbose
          displayName: Run all unit tests

      # Run ComponentGovernance
      - task: ComponentGovernanceComponentDetection@0
        inputs:
          scanType: 'Register'
          verbosity: 'Verbose'
          alertWarningLevel: 'High'

    # Build PyTorch and produce artifacts for verification stage
    - ${{ if eq(parameters.is_official_build, 'True') }}:
      # Build PyTorch from source in install mode with Ninja and exclude test binaries
      - script: call activate $(configuration) && python setup.py install
        displayName: Build PyTorch from source without test binaries

      # Package PyTorch Wheel
      - script: call activate $(configuration) && python setup.py bdist_wheel
        displayName: Package PyTorch Wheel

      # Publish PyTorch Wheel
      - task: PublishPipelineArtifact@1
        inputs:
          targetPath: $(Build.SourcesDirectory)\dist\
          artifactName: Build_$(Build.BuildNumber)_$(configuration)
        displayName: Publish PyTorch Wheel to Pipeline Artifacts

  # Verification Stage
  - ${{ if eq(parameters.verify_stage, 'True') }}:
    # Download PyTorch Wheel
    - task: DownloadPipelineArtifact@2
      inputs:
        artifact: Build_$(Build.BuildNumber)_$(configuration)
        path: $(Build.SourcesDirectory)\verify
      displayName: Download PyTorch Wheel

    # Install PyTorch Wheel on Windows
    - script: |
        call activate $(configuration)
        cd $(Build.SourcesDirectory)\verify
        dir torch*win*.whl /b > whl.txt
        set /p whl= < whl.txt
        python -m pip install %whl%
      displayName: Install PyTorch Wheel

    # Ensure PyTorch installed correctly from produced wheel
    - script: |
        call activate $(configuration)
        cd $(Build.SourcesDirectory)\verify
        python -c "import torch; print('Installed Torch version: ' + torch.__version__)"
      displayName: Check PyTorch correctly installed from wheel

  # Publishing stage
  - ${{ if eq(parameters.publish_stage, 'True') }}:
    # Download PyTorch Wheel
    - task: DownloadPipelineArtifact@2
      inputs:
        artifact: Build_$(Build.BuildNumber)_$(configuration)
        path: $(Build.SourcesDirectory)\publish
      displayName: Download PyTorch Wheel

    # Set up Azure Artifacts for Windows
    # The pip install --upgrade command is a bug fix for Azure CLI on Windows
    # More info: https://github.com/Azure/azure-cli/issues/16858
    - script: |
        pip install --upgrade pip --target \opt\az\lib\python3.6\site-packages\
        az extension add -n azure-devops
      displayName: Set up Azure Artifacts download on Windows

    # Publish wheel to Azure Artifacts
    # The flag continueOnError=true is needed as the artifact to be published
    # may already exist, because the artifact is differentiated based on the
    # last commit date.
    - script: |
        set /p TORCH_VERSION= < version.txt
        cd $(Build.SourcesDirectory)\publish
        git rev-parse --short HEAD > last_commit.txt && set /p LAST_COMMIT= < last_commit.txt
        git log -1 --pretty=%ad --date=format:%Y%m%d > last_commit_date.txt && set /p LAST_COMMIT_DATE= < last_commit_date.txt
        dir torch*win*.whl /b > whl.txt && set /p TORCH_WHEEL= < whl.txt
        echo %ADOTOKEN% | az devops login
        az artifacts universal publish --organization %AZURE_DEVOPS_ARTIFACTS_ORGANIZATION% --project %AZURE_DEVOPS_ARTIFACTS_PROJECT% --scope project --feed "PyTorch" --name %TORCH_WHEEL% --description "PyTorch Official Build Artifact" --version %TORCH_VERSION:~0,5%-%LAST_COMMIT_DATE%-%LAST_COMMIT% --path .
      env:
        ADOTOKEN: $(AZURE_DEVOPS_CLI_PAT)
      continueOnError: true
      displayName: Upload PyTorch nigthly package to Azure Artifacts
