# PyTorch build steps template with Unix images Azure DevOps Instances
#
# This build depends on 5 parameters set as an environment variables in the pipeline:
#   - AZURE_DEVOPS_CLI_PAT: Secret var for authenticating to Azure DevOps
#   - AZURE_STORAGE_KEY: Secret var for authenticating to Azure Storage
#   - _TS_CLONE_P, _TS_P, _TS_SM_P: Secret vars for specific unit tests

parameters:
  name: ''
  pool: ''
  container_endpoint: ''
  customMatrixes: ''

jobs:
- job: ${{parameters.name}}
  timeoutInMinutes: 600
  strategy:
    matrix:
      ${{ insert }}: ${{parameters.customMatrixes}}
  pool:
    name: ${{ parameters.pool}}
  variables:
    DECODE_PERCENTS: false

  steps:
  # Don't checkout repo contents to save time and CPU compute. Environment variables
  # related to checkout branch such as $(BUILD_SOURCEBRANCH) are still available.
  - checkout: none

  # Delete pytorch_tests repo from previous builds if exists
  - bash: rm -rf pytorch_tests/
    displayName: Delete pytorch_tests repo from previous builds if exists

  # Clone PyTorch Tests repository
  - bash: |
      B64_PAT=$(echo -n ":$_ADOTOKEN" | base64)
      git -c http.extraHeader="Authorization: Basic ${B64_PAT}" clone $(AZURE_DEVOPS_PYTORCH_TESTS_REPO_URL)
      cd pytorch_tests
      git checkout $(PYTORCH_TESTS_CHECKOUT_BRANCH)
    env:
      _ADOTOKEN: $(AZURE_DEVOPS_CLI_PAT)
    displayName: Clone PyTorch Tests repo

  # Run PyTorch Unit Tests
  - bash: bash $(Build.SourcesDirectory)/pytorch_tests/scripts/linux/run.sh
    env:
      _AZURE_STORAGE_KEY: $(AZURE_STORAGE_KEY)
      _TS_CLONE_P: $(TS_CLONE_PASSWORD)
      _TS_P: $(TS_PAT)
      _TS_SM_P: $(TS_SM_PAT)
      _AZUREML_CLONE_PASSWORD: $(AZUREML_CLONE_PASSWORD)
      _SPPASSWORD: $(SPPASSWORD)
    displayName: Run PyTorch Unit Tests

  # Tests results are available outside the docker container since
  # the current directory is mounted as a volume of the container.
  - task: PublishTestResults@2
    condition: always()
    inputs:
      testResultsFiles: '**/test-*.xml'
      testRunTitle: 'Publish test results for Python'
