# Initiate 5 agentless-server waiting jobs to check on the
# status of PR artifact builds, for a maximum wait time of
# 11*60 min=660 mins. These jobs will pass immediately
# once targeted CircleCI build is ready.

jobs:
- job: checkjob1
  pool: server
  timeoutInMinutes: 60
  continueOnError: true
  steps:
  - template: wheel-wait-job-template.yml

- job: checkjob2
  pool: server
  timeoutInMinutes: 60
  dependsOn: checkjob1
  continueOnError: true
  steps:
  - template: wheel-wait-job-template.yml

- job: checkjob3
  pool: server
  timeoutInMinutes: 60
  dependsOn: checkjob2
  continueOnError: true
  steps:
  - template: wheel-wait-job-template.yml

- job: checkjob4
  pool: server
  timeoutInMinutes: 60
  dependsOn: checkjob3
  continueOnError: true
  steps:
  - template: wheel-wait-job-template.yml

- job: checkjob5
  pool: server
  timeoutInMinutes: 60
  dependsOn: checkjob4
  continueOnError: true
  steps:
  - template: wheel-wait-job-template.yml

- job: checkjob6
  pool: server
  timeoutInMinutes: 60
  dependsOn: checkjob5
  continueOnError: true
  steps:
  - template: wheel-wait-job-template.yml

- job: checkjob7
  pool: server
  timeoutInMinutes: 60
  dependsOn: checkjob6
  continueOnError: true
  steps:
  - template: wheel-wait-job-template.yml

- job: checkjob8
  pool: server
  timeoutInMinutes: 60
  dependsOn: checkjob7
  continueOnError: true
  steps:
  - template: wheel-wait-job-template.yml

- job: checkjob9
  pool: server
  timeoutInMinutes: 60
  dependsOn: checkjob8
  continueOnError: true
  steps:
  - template: wheel-wait-job-template.yml

- job: checkjob10
  pool: server
  timeoutInMinutes: 60
  dependsOn: checkjob9
  continueOnError: true
  steps:
  - template: wheel-wait-job-template.yml

- job: checkjob11
  pool: server
  timeoutInMinutes: 60
  dependsOn: checkjob10
  continueOnError: true
  steps:
  - template: wheel-wait-job-template.yml
