# Disable built-in rules
MAKEFLAGS += -rR

AS	= $(CROSS_COMPILE)as
AR      = $(CROSS_COMPILE)ar
LD	= $(CROSS_COMPILE)ld
CC	= $(CROSS_COMPILE)gcc
CFLAGS += -Wall -I$(CURDIR) -I$(COMMON_DIR) -fPIC

ifeq ($(BIT32),y)
CFLAGS += -g -Wall -O2 -m32 -I$(CURDIR)
else
CFLAGS += -g -Wall -O2 -m64 -I$(CURDIR)
endif

ifdef DEBUG
 CFLAGS += -g -pg -DDEBUG
else
 CFLAGS += -O2
endif
